package com.codingpixel.undiscoveredarchives.network

object ApiTags {

    const val LOGIN = "Login"
    const val GET_COUNTRIES = "GetCountries"
    const val GET_STATES = "GetStates"
    const val GET_CITIES = "GetCities"
    const val SOCIAL_LOGIN = "SocialLogin"
    const val REGISTER = "Register"
    const val FORGOT_PASSWORD = "ForgotPassword"
    const val RESEND_OTP = "ResendOtp"
    const val VERIFY_OTP = "VerifyOTP"
    const val RESET_PASSWORD = "ResetPassword"
    const val GET_NOTIFICATIONS = "GetNotifications"
    const val GET_CATEGORIES_WITH_PRODUCTS = "GetCategoriesWithProducts"
    const val GET_CATEGORIES = "GetCategories"
    const val GET_DESIGNERS = "GetDesigners"
    const val GET_FEATURED_PRODUCTS = "GetFeaturedProducts"
    const val GET_FAVORITE_PRODUCTS = "GetFavoriteProducts"
    const val GET_FAVORITE_DESIGNER = "GetFavoriteDesigners"
    const val ADD_PRODUCT_TO_FAVORITES = "AddProductToFavorites"
    const val ADD_DESIGNER_TO_FAVORITES = "AddDesignerToFavorites"
    const val GET_PROFILE = "GetProfile"
    const val SAVE_PROFILE = "SaveProfile"
    const val GET_ALL_PRODUCTS = "GetAllProducts"
    const val GET_PRODUCT_DETAIL = "GetProductDetail"
    const val GET_DRAFTS_PRODUCTS = "GetDraftsProducts"
    const val GET_TRASHED_PRODUCTS = "GetTrashedProducts"
    const val GET_PUBLISHED_PRODUCTS = "GetPublishedProducts"
    const val DELETE_PRODUCT = "DeleteProduct"
    const val RESTORE_TRASHED_PRODUCT = "RestoreTrashedProduct"
    const val UPDATE_PRODUCT_STATUS = "UpdateProductStatus"
    const val GET_PRODUCT_GRADIENTS = "GetProductGradients"
    const val CREATE_PRODUCTS = "CreateProducts"
    const val GET_SETTINGS = "GetSettings"
    const val BECOME_SELLER = "BecomeSeller"
    const val REGISTER_DEVICE = "RegisterDevice"
    const val LOGOUT = "Logout"
    const val DELETE_PRODUCT_FILES = "DeleteProductFiles"
    const val NOTIFICATION_SETTINGS = "NotificationSettings"
    const val GET_ALL_DESIGNERS = "GetAllDesigners"

}